global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using NSubstitute;
global using Relecloud.Models.ConcertContext;
global using Relecloud.Models.Events;
global using Relecloud.TicketRenderer.Models;
global using Relecloud.TicketRenderer.Services;
global using Relecloud.TicketRenderer.TestHelpers;
global using Xunit;